### ISSUE TITLE
README idea

### ISSUE THREAD

**Issue by RemcoHalman** [h3cksamrat/FacebookAutomatedComment#3]
I would recommend using a virtual environment. Be it the default `python3 -m venv <env name>`, virtualenv or pipenv(not my recommendation)

**Comment by h3cksamrat** [comment]
Sorry, I didn't get your idea. Can you please elaborate it and explain it, why?

**Comment by RemcoHalman** [comment]
@h3cksamrat let me elaborate on it 😁 I like to use a virtual environment to split of the packages from the main python installation. 

This is could also be usefull to prevent things like conflicting packages

Below is an idea.

_____

If `git` and `python` are installed I recommend using a virtual environment to split all packages of the main installation. 

```bash
python3 -m venv venv
source /venv/bin/activate
pip install -r requirements.txt (if there is one else skip this line)
```

When all dependancies are installed run `python main.py`

**Comment by h3cksamrat** [comment]
Thank You @RemcoHalman will sure do it.
